### ISSUE TITLE
cctrluser: running any command got this error: Could not connect to API...

### ISSUE THREAD

**Issue by btootoonchi** [cloudControl/cctrl#10]
Hi, 
I tried different type of cctrluser command and got the error:"Could not connect to API..."
for example: cctrluser create, cctrluser activate, cctrluser key.add

I have an account in CouldControl.com, and I have already activated it by clicking the link that was sent to email address. but in the command line any command does not work. 
I have installed Git and ccrtl. The OS is windows 8 Pro - 64-bit.

Please help me.

Thanks
Bobby

**Comment by fern4lvarez** [comment]
Hi @rs3d,
We haven't heard back from you regarding this case. At this time, we're closing this issue. However, if you're still experiencing issues, we want to hear from you! Please re-open this issue for continued support.
