### ISSUE TITLE
Is ez_setup.py still needed?

### ISSUE THREAD

**Issue by fern4lvarez** [cloudControl/cctrl#62]
What's its use case?

**Comment by sfriesel** [comment]
afaics from the commit history it was never used and it's badly outdated too

**Comment by fern4lvarez** [comment]
Well, and it's pretty much a copy of this file http://peak.telecommunity.com/dist/ez_setup.py

Truth is that it's used on this [fallback block](https://github.com/cloudControl/cctrl/blob/master/setup.py#L12-L18) whenever `setuptools` is not installed. But I couldn't tell how many users are using `cctrl` without `setuptools` installed, specially when we recommend using `easy_install` for installing `pip` on our [official documentation](https://github.com/cloudControl/documentation/blob/master/Platform%20Documentation.md#quick-installation-linuxmac).

**Comment by TooAngel** [comment]
I think it is outdated, let's remove it
