### ISSUE TITLE
cctrlapp won't ask for the email address

### ISSUE THREAD

**Issue by cauboy** [cloudControl/cctrl#67]
Hey,

I'm using
```bash
$ cctrlapp -v
cctrlapp 1.16.0 using pycclib 1.6.1
```
. Whenever I want to run some commands e.g. ```cctrlapp APP_NAME/DEPLOYMENT_NAME addon.creds``` I am asked for a password but not for the email address. Therefore this results in the following:
```bash
$ cctrlapp APP_NAME/DEPLOYMENT_NAME addon.creds
Password:
The authorization failed, check your e-mail address and password.
```

What's wrong?

**Comment by schu** [comment]
Hi, could you send a mail to support@cloudcontrol.de? Thanks!

**Comment by fern4lvarez** [comment]
cctrlapp won't ask for email addres when this is set on the `~/.cloudControl/user.cfg` file. Working as expected.
